export const nanoNodeNames = {
  doc: 'doc',
  paragraph: 'paragraph',
  heading: 'heading',
  quote: 'quote',
  callout: 'callout',
  customBlock: 'custom_block',
  todo: 'todo',
  listItem: 'list_item',
  footnote: 'footnote',
  codeBlock: 'code_block',
  mathBlock: 'math_block',
  bookmark: 'bookmark',
  noteRef: 'note_ref',
  tagRef: 'tag_ref',
  attachment: 'attachment',
  divider: 'divider',
  image: 'image',
  table: 'table',
  mention: 'mention',
  hardBreak: 'hard_break',
  text: 'text',
} as const

export const nanoMarkNames = {
  bold: 'strong',
  italic: 'em',
  underline: 'underline',
  strike: 'strike',
  highlight: 'highlight',
  code: 'code',
  tag: 'tag',
  noteLink: 'note_link',
  math: 'math',
  footnoteRef: 'footnote_ref',
  link: 'link',
  source: 'source',
} as const
