export {
  NanoDeckMetadataSchema,
  NanoDeckSchema,
  NanoSlideRegionKindSchema,
  NanoSlideRegionSchema,
  NanoSlideSchema,
  createEmptyNanoDeck,
  createNanoDeck,
  emptyNanoDeck,
  type NanoDeck,
  type NanoDeckEngine,
  type NanoDeckMetadata,
  type NanoSlide,
  type NanoSlideRegion,
  type NanoSlideRegionKind,
} from './nano-deck'
