export {
  NanoBlockSchema,
  NanoDeckMetadataSchema,
  NanoDeckSchema,
  NanoDocumentSchema,
  NanoMarkSchema,
  NanoSlideRegionKindSchema,
  NanoSlideRegionSchema,
  NanoSlideSchema,
  blockTextPointer,
  blocksPointer,
  createEmptyNanoDocument,
  createEmptyNanoDeck,
  createNanoDeck,
  createNanoDocument,
  emptyNanoDeck,
  emptyNanoDocument,
  point,
  pointOffset,
  pointPath,
  replaceBlocksPatch,
  selectionSnap,
  type NanoDeck,
  type NanoDeckEngine,
  type NanoDeckMetadata,
  type NanoBlock,
  type NanoDocument,
  type NanoDocumentEngine,
  type NanoMark,
  type NanoSlide,
  type NanoSlideRegion,
  type NanoSlideRegionKind,
} from './core/nano-core'
export {
  createNanoView,
  type NanoViewHandle,
  type NanoViewOptions,
} from './view/nano-view'
export {
  createNanoEditorKit,
  defaultNanoEditorKit,
  defaultNanoViewFeatures,
  kitHasViewFeature,
  type CreateNanoEditorKitOptions,
  type NanoEditorKit,
  type NanoViewFeatureId,
} from './engine/index'
export { basicCapability } from './capabilities/basic/capability'
export { todoCapability } from './capabilities/todo/capability'
export {
  nanoDocumentFromProseMirror,
  prosemirrorDocFromNano,
  nanoBlocksFromProseMirror,
} from './adapters/prosemirror/prosemirror-nano'
export {
  nanoDocumentFromMarkdown,
  nanoDeckFromMarkdown,
  nanoMarkdownBlocksFromDocument,
  nanoMarkdownFromDeck,
  nanoMarkdownFromDocument,
  type NanoMarkdownBlockEntry,
} from './codecs/markdown/nano-markdown'
export {
  nanoDocumentIndex,
  nanoDocumentIndexText,
  nanoDocumentSearch,
  type AttachmentIndexEntry,
  type BacklinkIndexEntry,
  type ImageIndexEntry,
  type IndexEntry,
  type NanoDocumentIndex,
  type NanoDocumentSearchResult,
  type NanoSpecialSearch,
  type TableIndexEntry,
} from './indexing/nano-document-index'
