export {
  NanoBlockSchema,
  NanoDeckMetadataSchema,
  NanoDeckSchema,
  NanoDocumentSchema,
  NanoMarkSchema,
  NanoSlideRegionKindSchema,
  NanoSlideRegionSchema,
  NanoSlideSchema,
  blockTextPointer,
  blocksPointer,
  createEmptyNanoDocument,
  createEmptyNanoDeck,
  createNanoDeck,
  createNanoDocument,
  emptyNanoDeck,
  emptyNanoDocument,
  point,
  pointOffset,
  pointPath,
  replaceBlocksPatch,
  selectionSnap,
  type NanoDeck,
  type NanoDeckEngine,
  type NanoDeckMetadata,
  type NanoBlock,
  type NanoDocument,
  type NanoDocumentEngine,
  type NanoMark,
  type NanoSlide,
  type NanoSlideRegion,
  type NanoSlideRegionKind,
} from './core/nano-core'
export {
  createNanoDeckView,
  createNanoView,
  type NanoDeckViewHandle,
  type NanoDeckViewOptions,
  type NanoViewHandle,
  type NanoViewOptions,
} from './view/nano-view'
export {
  createNanoEditorKit,
  defaultNanoEditorKit,
  defaultNanoViewFeatures,
  kitHasViewFeature,
  type CreateNanoEditorKitOptions,
  type NanoEditorKit,
  type NanoViewFeatureId,
} from './engine/index'
export {
  editorPartCatalog,
  editorPartCatalogById,
  editorPartsByCategory,
  type EditorPartCatalogItem,
  type EditorPartCategory,
  type EditorPartSurface,
} from './assembly/part-catalog'
export { basicCapability } from './capabilities/basic/capability'
export { todoCapability } from './capabilities/todo/capability'
export {
  nanoDocumentFromProseMirror,
  prosemirrorDocFromNano,
  nanoBlocksFromProseMirror,
} from './adapters/prosemirror/prosemirror-nano'
export {
  nanoDocumentFromMarkdown,
  nanoDeckFromMarkdown,
  nanoMarkdownBlocksFromDocument,
  nanoMarkdownFromDeck,
  nanoMarkdownFromDocument,
  type NanoMarkdownBlockEntry,
} from './codecs/markdown/nano-markdown'
export {
  nanoDocumentIndex,
  nanoDocumentIndexText,
  nanoDocumentSearch,
  type AttachmentIndexEntry,
  type BacklinkIndexEntry,
  type ImageIndexEntry,
  type IndexEntry,
  type NanoDocumentIndex,
  type NanoDocumentSearchResult,
  type NanoSpecialSearch,
  type TableIndexEntry,
} from './indexing/nano-document-index'
export {
  collapseInlineEditSelection,
  inlineEditHasLineBreak,
  inlineEditHistoryDirectionFromInputType,
  inlineEditHistoryDirectionFromKeydown,
  inlineEditSelectionOffset,
  inlineEditSingleLineText,
  inlineEditTextPositionAtOffset,
  insertInlineEditText,
  isInlineEditLineBreakInput,
  restoreInlineEditFocus,
  type InlineEditHistoryDirection,
  type InlineEditTextPosition,
} from './inline-edit/index'
export {
  inlineAutocompleteContextFromInput,
  inlineAutocompleteContextFromMode,
  inlineAutocompleteContextFromTrigger,
  inlineAutocompleteInsertedText,
  inlineAutocompleteMatchFromText,
  insertInlineAutocompleteText,
  replaceInlineAutocompleteText,
  type InlineAutocompleteContext,
  type InlineAutocompleteInsertOptions,
  type InlineAutocompleteMatch,
  type InlineAutocompleteTrigger,
} from './inline-autocomplete/index'
export {
  autocompleteOptionMatches,
  createAutocomplete,
  createAutocompleteSurface,
  movedAutocompleteIndex,
  nearestEnabledAutocompleteIndex,
  visibleAutocompleteOptions,
  type Autocomplete,
  type AutocompleteOption,
  type AutocompleteOptions,
  type AutocompleteState,
  type AutocompleteSurface,
  type AutocompleteSurfaceClasses,
  type AutocompleteSurfaceElements,
  type AutocompleteSurfaceOption,
  type AutocompleteSurfaceOptions,
} from './autocomplete/index'
export {
  createSuggestionSurface,
  movedSuggestionIndex,
  nearestEnabledSuggestionIndex,
  suggestionOptionMatches,
  visibleSuggestionOptions,
  type SuggestionSurface,
  type SuggestionSurfaceClasses,
  type SuggestionSurfaceElements,
  type SuggestionSurfaceOption,
  type SuggestionSurfaceOptions,
} from './suggestion/index'
