import type { EditorPartCatalogItem } from './part-catalog-types'

export const inlinePartCatalog = [
  {
    id: 'mark.bold',
    label: 'Bold mark',
    category: 'inline',
    summary: 'Strong text mark preserving asterisk or underscore source marker.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'input-rule'],
    pairsWith: ['input.markdown-shortcuts'],
  },
  {
    id: 'mark.italic',
    label: 'Italic mark',
    category: 'inline',
    summary: 'Emphasis mark preserving asterisk or underscore source marker.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'input-rule'],
    pairsWith: ['input.markdown-shortcuts'],
  },
  {
    id: 'mark.underline',
    label: 'Underline mark',
    category: 'inline',
    summary: 'Bear-style underline mark written with single tilde delimiters.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'input-rule'],
    pairsWith: ['view.markdown-source'],
  },
  {
    id: 'mark.strike',
    label: 'Strike mark',
    category: 'inline',
    summary: 'Strikethrough mark using double tilde Markdown delimiters.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'input-rule'],
    pairsWith: ['input.markdown-shortcuts'],
  },
  {
    id: 'mark.highlight',
    label: 'Highlight mark',
    category: 'inline',
    summary: 'Inline highlight mark using double equals delimiters.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'input-rule'],
    pairsWith: ['input.markdown-shortcuts'],
  },
  {
    id: 'mark.code',
    label: 'Inline code mark',
    category: 'inline',
    summary: 'Inline code span preserving multi-backtick source length.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'input-rule'],
    pairsWith: ['codec.markdown-source-preservation'],
  },
  {
    id: 'mark.link',
    label: 'Link mark',
    category: 'inline',
    summary: 'Inline Markdown link and URL autolink preserving title and destination style.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'index'],
    pairsWith: ['index.search-query', 'block.bookmark'],
  },
  {
    id: 'mark.tag',
    label: 'Tag mark',
    category: 'inline',
    summary: 'Inline Bear tag with hierarchy support and multi-word tag syntax.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'index'],
    pairsWith: ['index.tags', 'block.tag-ref'],
  },
  {
    id: 'mark.note-link',
    label: 'Note link mark',
    category: 'inline',
    summary: 'Inline wiki link with heading target and optional alias.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'index'],
    pairsWith: ['index.backlinks', 'block.note-ref'],
  },
  {
    id: 'mark.math',
    label: 'Inline math mark',
    category: 'inline',
    summary: 'Inline formula mark using dollar-delimited Markdown.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'index'],
    pairsWith: ['block.math', 'index.search-query'],
  },
  {
    id: 'mark.footnote-ref',
    label: 'Footnote reference mark',
    category: 'inline',
    summary: 'Inline footnote reference linked to footnote definition blocks.',
    surfaces: ['document-schema', 'mark-option', 'markdown-codec', 'prosemirror-adapter', 'index'],
    pairsWith: ['block.footnote'],
  },
] as const satisfies readonly EditorPartCatalogItem[]
